# installer for Weather34 skin
# based on installer for exfoliation
# by Matthew Wall
# Modified for Weather34 skin by Ian Millard <steepleian@gmail.com> 2019

from setup import ExtensionInstaller

def loader():
    return Weather34Installer()

class Weather34Installer(ExtensionInstaller):
    def __init__(self):
        super(Weather34Installer, self).__init__(
            version="09",
            name='Weather34',
            description='Weather34 skin',
            author="Steepleian",
            author_email="steepleian@gmail.com",
            process_services='user.weather34.Weather34RealTime',
		
            config={
                'StdReport': {
                    'Weather34Report': {
                        'skin':'Weather34',
                        'HTML_ROOT':'weather34',
                              'Units': {
                                  'Groups': {
                                      'group_altitude': 'meter',
                                      'group_degree_day': 'degree_C_day',
                                      'group_pressure': 'hPa',
                                      'group_rain': 'mm',
                                      'group_rainrate': 'mm_per_hour',
                                      'group_speed': 'meter_per_second',
                                      'group_speed2': 'meter_per_second2',
                                      'group_temperature': 'degree_C'
				  
                            },
                                 'StringFormats': {
                                      'centibar': '%.0f',
                                      'cm': '%.2f',
                                      'cm_per_hour': '%.2f',
                                      'degree_C': '%.1f',
                                      'degree_F': '%.1f',
                                      'degree_compass': '%.0f',
                                      'foot': '%.0f',
                                      'hPa': '%.1f',
                                      'inHg': '%.3f',
                                      'inch': '%.2f',
                                      'inch_per_hour': '%.2f',
                                      'km_per_hour': '%.0f',
                                      'km_per_hour2': '%.1f',
                                      'knot': '%.0f',
                                      'knot2': '%.1f',
                                      'mbar': '%.1f',
                                      'meter': '%.0f',
                                      'meter_per_second': '%.1f',
                                      'meter_per_second2': '%.1f',
                                      'mile_per_hour': '%.0f',
                                      'mile_per_hour2': '%.1f',
                                      'mm': '%.1f',
                                      'mmHg': '%.1f',
                                      'mm_per_hour': '%.1f',
                                      'percent': '%.0f',
                                      'uv_index': '%.1f',
                                      'volt': '%.1f',
                                      'watt_per_meter_squared': '%.0f',
                                      'NONE': 'N/A'
				 
                            },'Labels': {
                                      'centibar': 'cb',
                                      'cm': 'cm',
                                      'cm_per_hour': 'cm/hr',
                                      'degree_C': '\u00B0 C',
                                      'degree_F': '\u00B0 F',
                                      'degree_compass': '\u00B0',
                                      'foot': 'feet',
                                      'hPa': 'hPa',
                                      'inHg': 'inHg',
                                      'inch': 'in',
                                      'inch_per_hour': 'in/hr',
                                      'km_per_hour': 'km/hr',
                                      'km_per_hour2': 'km/hr',
                                      'knot': 'knots',
                                      'knot2': 'knots',
                                      'mbar': 'mbar',
                                      'meter': 'meters',
                                      'meter_per_second': 'm/s',
                                      'meter_per_second2': 'm/s',
                                      'mile_per_hour': 'mph',
                                      'mile_per_hour2': 'mph',
                                      'mm': 'mm',
                                      'mmHg': 'mmHg',
                                      'mm_per_hour': 'mm/hr',
                                      'percent': '%',
                                      'uv_index': 'Index',
                                      'volt': 'V',
                                      'watt_per_meter_squared': 'W/m\u00B2',
                                      'NONE':      ''
                            }}}
                        },
            	'Weather34RealTime' : {
                    		'filename':'/var/www/html/weewx/w34realtime.txt',
				'unit_system':'METRICWX',
              			'binding':'loop',
				'exclude_fields':'rain',
            			'cache_directory':'/tmp',
				'cache_stale_time':'900'
		},
		    'Weather34WebServices' : {
                    	'filename':'/var/www/html/weewx/weather34/settings1.php'
						
		}	
            },
                
            files=[('bin/user', ['bin/user/lastrain.py',
                                 'bin/user/stats.py',
                                 'bin/user/weather34.py'
				 
                                ]
                    ),
                   ('skins/Weather34', ['skins/Weather34/skin.conf',
                                        
                                        'skins/Weather34/archivedata.php.tmpl'
                                         ]
                    ),
                   
                                      
                   ('skins/Weather34',       ['skins/Weather34/404.html',
                                                'skins/Weather34/CODE_OF_CONDUCT.md',
                                                'skins/Weather34/CONTRIBUTING.md',
                                                'skins/Weather34/README.md',
                                                'skins/Weather34/_config.yml',
                                                'skins/Weather34/advisory.php',
                                                'skins/Weather34/airqualitymodule.php',
                                                'skins/Weather34/aqiinfo.php',
                                                'skins/Weather34/aurora.php',
                                                'skins/Weather34/barometer.php',
                                                'skins/Weather34/barometeralmanac.php',
                                                'skins/Weather34/bio.php',
                                                'skins/Weather34/cam.php',
                                                'skins/Weather34/common.php', 
                                                'skins/Weather34/currentconditionsw34.php',
                                                'skins/Weather34/davisconsoleoutlook.php',
                                                'skins/Weather34/dsuvindex.php',
                                                'skins/Weather34/earthquake.php',
                                                'skins/Weather34/easyW34skinSetup.php',
                                                'skins/Weather34/eq.php',
                                                'skins/Weather34/eqlist.php',
                                                'skins/Weather34/favicon.ico',
                                                'skins/Weather34/forecast3ds.php',
                                                'skins/Weather34/forecast3wu.php',
                                                'skins/Weather34/forecast3wularge.php',
                                                'skins/Weather34/forecastdshour.php',
                                                'skins/Weather34/homeindoor.php',
                                                'skins/Weather34/index.php',
                                                'skins/Weather34/indoortemperature.php',
                                                'skins/Weather34/info.php',
                                                'skins/Weather34/license.txt',
                                                'skins/Weather34/lightning34.php',
                                                'skins/Weather34/w34CombinedData.php',
                                                'skins/Weather34/manifest.php',
                                                'skins/Weather34/max-mintemp.php',
                                                'skins/Weather34/max-minwind.php',
                                                'skins/Weather34/menu.php',
                                                'skins/Weather34/index.alt',
					      	'skins/Weather34/metar34get.php',
                                                'skins/Weather34/metarnearby.php', 
                                                'skins/Weather34/meteorshowers.php',
                                                'skins/Weather34/mooninfo.php',
                                                'skins/Weather34/moonphase.php',
                                                'skins/Weather34/notify.php',
                                                'skins/Weather34/outlookds.php',
                                                'skins/Weather34/outlookwu.php',
                                                'skins/Weather34/purpleair.php',
                                                'skins/Weather34/rainfall.php',
                                                'skins/Weather34/rainfallalmanac.php',
                                                'skins/Weather34/rainfallf-year-month.php',
                                                'skins/Weather34/settings.php',
                                                'skins/Weather34/settings1.default.php',  	
                                                'skins/Weather34/shared.php',
                                                'skins/Weather34/solaralmanac.php',
                                                'skins/Weather34/solaruvds.php',
                                                'skins/Weather34/solaruvwu.php',
                                                'skins/Weather34/stationinfo.php',
                                                'skins/Weather34/sun3.php',
                                                'skins/Weather34/sun4.php',
                                                'skins/Weather34/sw.js',
                                                'skins/Weather34/tempalmanac.php',
                                                'skins/Weather34/temperature.php',
                                                'skins/Weather34/temperaturein.php',
                                                'skins/Weather34/temperatureyear.php',
                                                'skins/Weather34/todaybarometersmall.php',
                                                'skins/Weather34/todayrainfallsmall.php',
                                                'skins/Weather34/todaytempsmall.php',
                                                'skins/Weather34/todaywindspeedsmall.php',
                                                'skins/Weather34/updater.php',
                                                'skins/Weather34/uvalmanac.php',
                                                'skins/Weather34/uvindex.php',
                                                'skins/Weather34/uvindexds.php',
                                                'skins/Weather34/uvindexwf.php',
                                                'skins/Weather34/uvindexwu.php',
                                                'skins/Weather34/uvsolar.php',
                                                'skins/Weather34/uvsolarbri.php',
                                                'skins/Weather34/weather34_template_info.php',
                                                'skins/Weather34/weather34clock.php',
                                                'skins/Weather34/weather34skydata.php',
                                                'skins/Weather34/weather34uvsolar.php',
                                                'skins/Weather34/weatherflow.php',
                                                'skins/Weather34/weatherflowuvsolar.php',
                                                'skins/Weather34/webcamsmall.php',
                                                'skins/Weather34/weewxcron.php',
					        
                                                'skins/Weather34/wflightning.php',
                                                'skins/Weather34/windalmanac.php',
                                                'skins/Weather34/windgustyear.php',
                                                'skins/Weather34/windspeeddirection.php',
                                                'skins/Weather34/windyradar.php',
                                                'skins/Weather34/windywind.php',
                                                'skins/Weather34/wxcharts.php']),
                   
                   
                   
                   ('skins/Weather34/css',   ['skins/Weather34/css/main.dark.css',
                                                'skins/Weather34/css/main.light.css',
                                                'skins/Weather34/css/wuoutlook.css',
					      	'skins/Weather34/css/easyweathersetup.css'
                                              ]
                    ),                    
                   ('skins/Weather34/css/aqi',   ['skins/Weather34/css/aqi/cold.svg',
                                                	'skins/Weather34/css/aqi/goodair.svg',
                                                	'skins/Weather34/css/aqi/hazair.svg',
                                                	'skins/Weather34/css/aqi/hot.svg',
                                                	'skins/Weather34/css/aqi/mild.svg',
                                                	'skins/Weather34/css/aqi/modair.svg',
                                                	'skins/Weather34/css/aqi/relativelymild.svg',
                                                	'skins/Weather34/css/aqi/uhair.svg',
                                                	'skins/Weather34/css/aqi/uhfsair.svg',
                                                	'skins/Weather34/css/aqi/vhair.svg',
                                                	'skins/Weather34/css/aqi/warm.svg']),
                   
                   ('skins/Weather34/css/darkskyicons',  ['skins/Weather34/css/darkskyicons/17.svg',
                                                			'skins/Weather34/css/darkskyicons/18.svg',
                                                			'skins/Weather34/css/darkskyicons/5.svg',
                                                			'skins/Weather34/css/darkskyicons/6.svg',
                                                			'skins/Weather34/css/darkskyicons/7.svg',
                                                			'skins/Weather34/css/darkskyicons/8.svg',
                                                			'skins/Weather34/css/darkskyicons/chancerain.svg',
                                                			'skins/Weather34/css/darkskyicons/clear-day.svg',
                                                			'skins/Weather34/css/darkskyicons/clear-night.svg',
                                                			'skins/Weather34/css/darkskyicons/cloudy.svg',
                                                			'skins/Weather34/css/darkskyicons/fog.svg',
                                                			'skins/Weather34/css/darkskyicons/hail.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_18.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_5.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_6.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_7.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_8.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_chancerain.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_clear-day.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_clear-night.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_cloudy.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_fog.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_hail.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_partly-cloudy-day.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_partly-cloudy-night.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_rain.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_sleet.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_snow.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_thunderstorm.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_tornado.svg',
                                                			'skins/Weather34/css/darkskyicons/nt_wind.svg',
                                                			'skins/Weather34/css/darkskyicons/partly-cloudy-day.svg',
                                                			'skins/Weather34/css/darkskyicons/partly-cloudy-night.svg',
                                                			'skins/Weather34/css/darkskyicons/rain.svg',
                                                			'skins/Weather34/css/darkskyicons/sleet.svg',
                                                			'skins/Weather34/css/darkskyicons/snow.svg',
                                                			'skins/Weather34/css/darkskyicons/thunderstorm.svg',
                                                			'skins/Weather34/css/darkskyicons/tornado.svg',
                                                			'skins/Weather34/css/darkskyicons/wind.svg']),
                   
                   ('skins/Weather34/css/fonts',  ['skins/Weather34/css/fonts/clock3-webfont.woff',
                                                       'skins/Weather34/css/fonts/clock3-webfont.woff2',
                                                       'skins/Weather34/css/fonts/clock3.ttf',
                                                       'skins/Weather34/css/fonts/clock3.ttf',
                                                       'skins/Weather34/css/fonts/sanfranciscodisplay-regular-webfont.woff',
                                                       'skins/Weather34/css/fonts/verbatim-regular.svg',
                                                       'skins/Weather34/css/fonts/verbatim-regular.ttf',
                                                       'skins/Weather34/css/fonts/verbatim-regular.woff',
                                                       'skins/Weather34/css/fonts/verbatim-regular.woff2',
                                                       'skins/Weather34/css/fonts/weathertext.eot',
                                                       'skins/Weather34/css/fonts/weathertext.svg',
                                                       'skins/Weather34/css/fonts/weathertext.woff',
                                                       'skins/Weather34/css/fonts/weathertext.woff2']),
                   
                   ('skins/Weather34/css/icons',  ['skins/Weather34/css/icons/airport.svg',
                                                			
                                                			'skins/Weather34/css/icons/breezy.svg',
                                                			'skins/Weather34/css/icons/chanceflurries.svg',
                                                			'skins/Weather34/css/icons/chancefog.svg',
                                                			'skins/Weather34/css/icons/chancerain.svg',
                                                			'skins/Weather34/css/icons/chancesleet.svg',
                                                			'skins/Weather34/css/icons/chancesnow.svg',
                                                			'skins/Weather34/css/icons/chancetstorm.svg',
                                                			'skins/Weather34/css/icons/chancetstorms.svg',
                                                			'skins/Weather34/css/icons/clear-day.svg',
                                                			'skins/Weather34/css/icons/clear-night.svg',
                                                			'skins/Weather34/css/icons/clear.svg',
                                                			'skins/Weather34/css/icons/cloudy.svg',
                                                			'skins/Weather34/css/icons/dust.svg',
                                                			'skins/Weather34/css/icons/flurries.svg',
                                                			'skins/Weather34/css/icons/fog.svg',
                                                			'skins/Weather34/css/icons/foggy.svg',
                                                			'skins/Weather34/css/icons/foggywarning.svg',
                                                			'skins/Weather34/css/icons/gust.svg',
                                                			'skins/Weather34/css/icons/gusting.svg',
                                                			'skins/Weather34/css/icons/hail.svg',
                                                			'skins/Weather34/css/icons/haze.svg',
                                                			'skins/Weather34/css/icons/hazy.svg',
                                                			'skins/Weather34/css/icons/heavy-showers.svg',
                                                			'skins/Weather34/css/icons/heavyrain.svg',
                                                			'skins/Weather34/css/icons/light-showers.svg',
                                                			'skins/Weather34/css/icons/lightning.svg',
                                                			'skins/Weather34/css/icons/mostly-cloudy.svg',
                                                			'skins/Weather34/css/icons/mostlycloudy.svg',
                                                			'skins/Weather34/css/icons/mostlysunny.svg',
                                                			'skins/Weather34/css/icons/n_partlycloudy.svg',
                                                			'skins/Weather34/css/icons/nightnosun.svg',
                                                			'skins/Weather34/css/icons/nosun.svg',
                                                			'skins/Weather34/css/icons/nosunuv.svg',
                                                			'skins/Weather34/css/icons/nsvrtsra.svg',
                                                			'skins/Weather34/css/icons/nt_.svg',
                                                			'skins/Weather34/css/icons/nt_27.svg',
                                                       		'skins/Weather34/css/icons/nt_28.svg',
                                                      		'skins/Weather34/css/icons/nt_29.svg',
                                                			'skins/Weather34/css/icons/nt_30.svg',
                                                			'skins/Weather34/css/icons/nt_chanceflurries.svg',
                                                			'skins/Weather34/css/icons/nt_chancefog.svg',
                                                			'skins/Weather34/css/icons/nt_chancerain.svg',
                                                			'skins/Weather34/css/icons/nt_chancesleet.svg',
                                                			'skins/Weather34/css/icons/nt_chancesnow.svg',
                                                			'skins/Weather34/css/icons/nt_chancetstorm.svg',
                                                			'skins/Weather34/css/icons/nt_chancetstorms.svg',
                                                			'skins/Weather34/css/icons/nt_clear.svg',
                                                			'skins/Weather34/css/icons/nt_clearclouds.svg',
                                                			'skins/Weather34/css/icons/nt_cloudy.svg',
                                                			'skins/Weather34/css/icons/nt_flurries.svg',
                                                			'skins/Weather34/css/icons/nt_fog.svg',
                                                			'skins/Weather34/css/icons/mostlycloudy.svg',
                                                			'skins/Weather34/css/icons/nt_haze.svg',
                                                			'skins/Weather34/css/icons/nt_hazy.svg',
                                                			'skins/Weather34/css/icons/nightnosun.svg',
                                                			'skins/Weather34/css/icons/nt_lightning.svg',
                                                			'skins/Weather34/css/icons/nt_mostlyclear.svg',
                                                			'skins/Weather34/css/icons/nt_mostlycloudy.svg',
                                                			'skins/Weather34/css/icons/nt_overcast.svg',
                                                			'skins/Weather34/css/icons/nt_partlycloudy.svg',
                                                       		'skins/Weather34/css/icons/nt_partlycloudyfew.svg',
                                                			'skins/Weather34/css/icons/nt_rain.svg',
                                                			'skins/Weather34/css/icons/gusting.svg',
                                                			'skins/Weather34/css/icons/nt_scatteredclouds.svg',
                                                			'skins/Weather34/css/icons/nt_sleet.svg',
                                                			'skins/Weather34/css/icons/nt_snow.svg',
                                                			'skins/Weather34/css/icons/nt_tstorm.svg',
                                                			'skins/Weather34/css/icons/nt_tstorms.svg',
                                                			'skins/Weather34/css/icons/nt_warm.svg',
                                                			'skins/Weather34/css/icons/nt_warmc.svg',
                                                			'skins/Weather34/css/icons/nt_windy.svg',
                                                			'skins/Weather34/css/icons/nt_windyclear.svg',
                                                			'skins/Weather34/css/icons/nt_windyovercast.svg',
                                                			'skins/Weather34/css/icons/n_partlycloudy.svg',
                                                			'skins/Weather34/css/icons/offiline.svg',
                                                			'skins/Weather34/css/icons/offline.svg',
                                                			'skins/Weather34/css/icons/offlineforecast.svg',
                                                			'skins/Weather34/css/icons/overcast.svg',
                                                			'skins/Weather34/css/icons/partly-cloudy-day.svg',
                                                			'skins/Weather34/css/icons/partly-cloudy-night.svg',
                                                       		'skins/Weather34/css/icons/partlycloudy.svg',
                                                      		'skins/Weather34/css/icons/partlycloudyfew.svg',
                                                			'skins/Weather34/css/icons/partlysunny.svg',
                                                			'skins/Weather34/css/icons/rain.svg',
                                                			'skins/Weather34/css/icons/rainbow.svg',
                                                			'skins/Weather34/css/icons/rainday.svg',
                                                			'skins/Weather34/css/icons/rainvp.svg',
                                                			'skins/Weather34/css/icons/scatteredclouds.svg',
                                                			'skins/Weather34/css/icons/sleet.svg',
                                                			'skins/Weather34/css/icons/snow.svg',
                                                			'skins/Weather34/css/icons/sunny.svg',
                                                			'skins/Weather34/css/icons/sunnyperiods.svg',
                                                			'skins/Weather34/css/icons/sunnywithclouds.svg',
                                                			'skins/Weather34/css/icons/sunposition.svg',
                                                			'skins/Weather34/css/icons/temp34.svg',
                                                			'skins/Weather34/css/icons/test.svg',
                                                			'skins/Weather34/css/icons/thunder.svg',
                                                			'skins/Weather34/css/icons/tstorm.svg',
                                                			'skins/Weather34/css/icons/tstorms.svg',
                                                			'skins/Weather34/css/icons/unknown.svg',
                                                			'skins/Weather34/css/icons/uvdark.svg',
                                                			'skins/Weather34/css/icons/uvhigh.svg',
                                                			'skins/Weather34/css/icons/uvnormal.svg',
                                                       			'skins/Weather34/css/icons/uvstrong.svg',
                                                			'skins/Weather34/css/icons/volcanoe.svg',
                                                			'skins/Weather34/css/icons/warm.svg',
                                                			'skins/Weather34/css/icons/wind.svg',
                                                			'skins/Weather34/css/icons/windsvg.svg',
                                                			'skins/Weather34/css/icons/windy.svg',
                                                			'skins/Weather34/css/icons/windyclear.svg',
                                                			'skins/Weather34/css/icons/windyovercast.svg',
                                                			'skins/Weather34/css/icons/windyrain.svg',
                                                			'skins/Weather34/css/icons/wuoffline.svg'
                                                       		]),
                   
                   ('skins/Weather34/css/mouse',   ['skins/Weather34/css/mouse/weather34bluecursor.png',
                                                        'skins/Weather34/css/mouse/weather34redcursor.png'
                                                       		]),
                   
                   ('skins/Weather34/css/rain',   ['skins/Weather34/css/rain/marker.svg',
                                                        'skins/Weather34/css/rain/rainmarker.svg',
                                                		'skins/Weather34/css/rain/water.svg'
                                                       		]),
                   
                   ('skins/Weather34/css/windicons',   ['skins/Weather34/css/windicons/.svg',
                                                        'skins/Weather34/css/windicons/avgw.svg'
                                                       		]),
                   
                   ('skins/Weather34/css/wuicons',  ['skins/Weather34/css/wuicons/0.svg',
                                                			
                                                			'skins/Weather34/css/wuicons/1.svg',
                                                			'skins/Weather34/css/wuicons/10.svg',
                                                			'skins/Weather34/css/wuicons/11.svg',
                                                			'skins/Weather34/css/wuicons/12.svg',
                                                			'skins/Weather34/css/wuicons/13.svg',
                                                			'skins/Weather34/css/wuicons/14.svg',
                                                			'skins/Weather34/css/wuicons/15.svg',
                                                			'skins/Weather34/css/wuicons/16.svg',
                                                			'skins/Weather34/css/wuicons/17.svg',
                                                			'skins/Weather34/css/wuicons/18.svg',
                                                			'skins/Weather34/css/wuicons/19.svg',
                                                			'skins/Weather34/css/wuicons/2.svg',
                                                			'skins/Weather34/css/wuicons/20.svg',
                                                			'skins/Weather34/css/wuicons/21.svg',
                                                			'skins/Weather34/css/wuicons/22.svg',
                                                			'skins/Weather34/css/wuicons/23.svg',
                                                			'skins/Weather34/css/wuicons/24.svg',
                                                			'skins/Weather34/css/wuicons/25.svg',
                                                			'skins/Weather34/css/wuicons/26.svg',
                                                			'skins/Weather34/css/wuicons/27.svg',
                                                			'skins/Weather34/css/wuicons/28.svg',
                                                			'skins/Weather34/css/wuicons/29.svg',
                                                			'skins/Weather34/css/wuicons/3.svg',
                                                			'skins/Weather34/css/wuicons/30.svg',
                                                			'skins/Weather34/css/wuicons/31.svg',
                                                			'skins/Weather34/css/wuicons/32.svg',
                                                			'skins/Weather34/css/wuicons/33.svg',
                                                			'skins/Weather34/css/wuicons/34.svg',
                                                			'skins/Weather34/css/wuicons/35.svg',
                                                			'skins/Weather34/css/wuicons/36.svg',
                                                			'skins/Weather34/css/wuicons/37.svg',
                                                			'skins/Weather34/css/wuicons/38.svg',
                                                			'skins/Weather34/css/wuicons/39.svg',
                                                			'skins/Weather34/css/wuicons/4.svg',
                                                			'skins/Weather34/css/wuicons/40.svg',
                                                			'skins/Weather34/css/wuicons/41.svg',
                                                       		'skins/Weather34/css/wuicons/42.svg',
                                                      		'skins/Weather34/css/wuicons/43.svg',
                                                			
                                                			'skins/Weather34/css/wuicons/45.svg',
                                                			'skins/Weather34/css/wuicons/46.svg',
                                                			'skins/Weather34/css/wuicons/47.svg',
                                                			
                                                			
                                                			'skins/Weather34/css/wuicons/5.svg',
                                                			'skins/Weather34/css/wuicons/6.svg',
                                                			'skins/Weather34/css/wuicons/7.svg',
                                                			'skins/Weather34/css/wuicons/8.svg',
                                                			'skins/Weather34/css/wuicons/9.svg',
                                                			'skins/Weather34/css/wuicons/nt_0.svg',
                                                			'skins/Weather34/css/wuicons/nt_1.svg',
                                                			'skins/Weather34/css/wuicons/nt_10.svg',
                                                			'skins/Weather34/css/wuicons/nt_11.svg',
                                                			'skins/Weather34/css/wuicons/nt_12.svg',
                                                			'skins/Weather34/css/wuicons/nt_13.svg',
                                                			'skins/Weather34/css/wuicons/nt_14.svg',
                                                			'skins/Weather34/css/wuicons/nt_15.svg',
                                                			'skins/Weather34/css/wuicons/nt_16.svg',
                                                			'skins/Weather34/css/wuicons/nt_17.svg',
                                                			'skins/Weather34/css/wuicons/nt_18.svg',
                                                       		'skins/Weather34/css/wuicons/nt_19.svg',
                                                			'skins/Weather34/css/wuicons/nt_2.svg',
                                                			'skins/Weather34/css/wuicons/nt_20.svg',
                                                			'skins/Weather34/css/wuicons/nt_21.svg',
                                                			'skins/Weather34/css/wuicons/nt_22.svg',
                                                			'skins/Weather34/css/wuicons/nt_23.svg',
                                                			'skins/Weather34/css/wuicons/nt_24.svg',
                                                			
                                                			'skins/Weather34/css/wuicons/nt_26.svg',
                                                			'skins/Weather34/css/wuicons/nt_27.svg',
                                                			'skins/Weather34/css/wuicons/nt_28.svg',
                                                			'skins/Weather34/css/wuicons/nt_29.svg',
                                                			'skins/Weather34/css/wuicons/nt_3.svg',
                                                			'skins/Weather34/css/wuicons/nt_30.svg',
                                                			'skins/Weather34/css/wuicons/nt_31.svg',
                                                			'skins/Weather34/css/wuicons/nt_32.svg',
                                                			'skins/Weather34/css/wuicons/nt_33.svg',
                                                			'skins/Weather34/css/wuicons/nt_34.svg',
                                                			'skins/Weather34/css/wuicons/nt_35.svg',
                                                			'skins/Weather34/css/wuicons/nt_36.svg',
                                                       		'skins/Weather34/css/wuicons/nt_37.svg',
                                                      		'skins/Weather34/css/wuicons/nt_38.svg',
                                                			'skins/Weather34/css/wuicons/nt_39.svg',
                                                			'skins/Weather34/css/wuicons/nt_4.svg',
                                                			'skins/Weather34/css/wuicons/nt_40.svg',
                                                			'skins/Weather34/css/wuicons/nt_41.svg',
                                                			'skins/Weather34/css/wuicons/nt_42.svg',
                                                			'skins/Weather34/css/wuicons/nt_43.svg',
                                                			
                                                			'skins/Weather34/css/wuicons/nt_45.svg',
                                                			'skins/Weather34/css/wuicons/nt_46.svg',
                                                			'skins/Weather34/css/wuicons/nt_47.svg',
                                                			'skins/Weather34/css/wuicons/nt_5.svg',
                                                			'skins/Weather34/css/wuicons/nt_6.svg',
                                                			'skins/Weather34/css/wuicons/nt_7.svg',
                                                			'skins/Weather34/css/wuicons/nt_8.svg',
                                                			'skins/Weather34/css/wuicons/nt_9.svg',
                                                			'skins/Weather34/css/wuicons/nt_lightning.svg',
                                                			
                                                			'skins/Weather34/css/wuicons/nt_tstorm.svg'
                                                       		]),

					  ('skins/Weather34/demodata',  ['skins/Weather34/demodata/realtime.txt']),

					  ('skins/Weather34/img',  		['skins/Weather34/img/Contents.json',
                                                			'skins/Weather34/img/DAVISCONSOLEVUEVECTOR.svg',
                                                			'skins/Weather34/img/Pi.jpg',
                                                			'skins/Weather34/img/WH2650.jpg',
                                                			'skins/Weather34/img/WH2650.svg',
                                                			'skins/Weather34/img/android-chrome-192x192.png',
                                                			'skins/Weather34/img/android-chrome-512x512.png',
                                                			'skins/Weather34/img/android-icon-144x144.png',
                                                			'skins/Weather34/img/android-icon-192x192.png',
                                                			'skins/Weather34/img/android-icon-36x36.png',
                                                			'skins/Weather34/img/android-icon-48x48.png',
                                                			'skins/Weather34/img/android-icon-72x72.png',
                                                			'skins/Weather34/img/android-icon-96x96.png',
                                                			'skins/Weather34/img/apple-icon-114x114.png',
                                                			'skins/Weather34/img/apple-icon-120x120.png',
                                                			'skins/Weather34/img/apple-icon-144x144.png',
                                                			'skins/Weather34/img/apple-icon-152x152.png',
                                                			'skins/Weather34/img/apple-icon-180x180.png',
                                                			'skins/Weather34/img/apple-icon-57x57.png',
                                                			'skins/Weather34/img/apple-icon-60x60.png',
                                                			'skins/Weather34/img/apple-icon-72x72.png',
                                                			'skins/Weather34/img/apple-icon-76x76.png',
                                                			'skins/Weather34/img/apple-icon-precomposed.png',
                                                			'skins/Weather34/img/apple-icon.png',
                                                			'skins/Weather34/img/apple-touch-icon-114x114.png',
                                                			'skins/Weather34/img/apple-touch-icon-120x120-precomposed.png',
                                                			'skins/Weather34/img/apple-touch-icon-120x120.png',
                                                			'skins/Weather34/img/apple-touch-icon-144x144.png',
                                                			'skins/Weather34/img/apple-touch-icon-152x152-precomposed.png',
                                                			'skins/Weather34/img/apple-touch-icon-152x152.png',
                                                			'skins/Weather34/img/apple-touch-icon-180x180-precomposed.png',
                                                			'skins/Weather34/img/apple-touch-icon-180x180.png',
                                                			'skins/Weather34/img/apple-touch-icon-57x57.png',
                                                			'skins/Weather34/img/apple-touch-icon-60x60-precomposed.png',
                                                			'skins/Weather34/img/apple-touch-icon-60x60.png',
                                                			'skins/Weather34/img/apple-touch-icon-72x72.png',
															'skins/Weather34/img/apple-touch-icon-76x76-precomposed.png',
                                                			'skins/Weather34/img/apple-touch-icon-76x76.png',
                                                			'skins/Weather34/img/apple-touch-icon-precomposed.png',
                                                			'skins/Weather34/img/apple-touch-icon.png',
                                                			'skins/Weather34/img/aqisvg.svg',
                                                			'skins/Weather34/img/browserconfig.xml',
                                                			'skins/Weather34/img/checkwx.svg',
															'skins/Weather34/img/code.txt',
                                                			'skins/Weather34/img/darksky.svg',
                                                			'skins/Weather34/img/davisvp2proconsole.svg',
                                                			'skins/Weather34/img/davisvue.svg',
                                                			'skins/Weather34/img/davisw34.svg',
                                                			'skins/Weather34/img/designedfor-1.svg',
                                                			'skins/Weather34/img/designedfordavisenvoy8x.svg',
															'skins/Weather34/img/designedfordavisvue.svg',
                                                			'skins/Weather34/img/designedformb.svg',
                                                			'skins/Weather34/img/easyweathersetupweather34.svg',
                                                			'skins/Weather34/img/favicon-128.png',
                                                			'skins/Weather34/img/favicon-16x16.png',
                                                			'skins/Weather34/img/favicon-196x196.png',
                                                			'skins/Weather34/img/favicon-32x32.png',
															'skins/Weather34/img/favicon-96x96.png',
                                                			'skins/Weather34/img/favicon.ico',
                                                			'skins/Weather34/img/hp2650.png',
                                                			'skins/Weather34/img/icon-weewx.svg',
                                                			'skins/Weather34/img/iframe.jpg',
                                                			'skins/Weather34/img/languages.png',
                                                			'skins/Weather34/img/lightningalert.svg',
															'skins/Weather34/img/manifest.json',
                                                			'skins/Weather34/img/moonphasesweather34svg.svg',
                                                			'skins/Weather34/img/mouse.png',
                                                			'skins/Weather34/img/mousedark.png',
                                                			'skins/Weather34/img/ms-icon-144x144.png',
                                                			'skins/Weather34/img/ms-icon-150x150.png',
                                                			'skins/Weather34/img/ms-icon-310x310.png',
															'skins/Weather34/img/ms-icon-70x70.png',
                                                			'skins/Weather34/img/mstile-144x144.png',
                                                			'skins/Weather34/img/mstile-150x150.png',
                                                			'skins/Weather34/img/mstile-310x150.png',
                                                			'skins/Weather34/img/mstile-310x310.png',
                                                			'skins/Weather34/img/mstile-70x70.png',
                                                			'skins/Weather34/img/nano.svg',
															'skins/Weather34/img/newlogo34.png',
                                                			
                                                			'skins/Weather34/img/purpleair.svg',
                                                			'skins/Weather34/img/safari-pinned-tab.svg',
                                                			'skins/Weather34/img/weather34_meta.png',
                                                			'skins/Weather34/img/weather34davisMBlogo.svg',
                                                			'skins/Weather34/img/weather34davisMBlogoold.svg',
															'skins/Weather34/img/weather34logo.svg',
                                                			'skins/Weather34/img/weather34vp2hardware.svg',
                                                			'skins/Weather34/img/weatherflow.svg',
                                                			'skins/Weather34/img/weatherlogo34.png',
                                                			'skins/Weather34/img/weatherlogo34.svg',
                                                			'skins/Weather34/img/wflogo.svg',
                                                			'skins/Weather34/img/wunderground.svg',
															'skins/Weather34/img/wunderground1.svg']),
                                                			
                      ('skins/Weather34/img/flags',  	[
                                                			'skins/Weather34/img/flags/a.svg',
                                                			'skins/Weather34/img/flags/ar.svg',
                                                			'skins/Weather34/img/flags/aus.svg',
                                                			'skins/Weather34/img/flags/b.svg',
                                                                        'skins/Weather34/img/flags/be.svg',
                                                			'skins/Weather34/img/flags/c.svg',
                                                			'skins/Weather34/img/flags/can.svg',
                                                			'skins/Weather34/img/flags/cat.svg',
                                                			'skins/Weather34/img/flags/cata.svg',
                                                			'skins/Weather34/img/flags/ch.svg',
                                                			'skins/Weather34/img/flags/dk.svg',
                                                			'skins/Weather34/img/flags/dl.svg',
                                                			'skins/Weather34/img/flags/en.svg',
                                                			'skins/Weather34/img/flags/eng.svg',
                                                			'skins/Weather34/img/flags/fr.svg',
                                                			'skins/Weather34/img/flags/gr.svg',
                                                			'skins/Weather34/img/flags/hu.svg',
                                                			'skins/Weather34/img/flags/iom.svg',
                                                			'skins/Weather34/img/flags/ire.svg',
                                                			'skins/Weather34/img/flags/it.svg',
                                                			'skins/Weather34/img/flags/nl.svg',
                                                			'skins/Weather34/img/flags/no.svg',
                                                			'skins/Weather34/img/flags/nz.svg',
                                                			'skins/Weather34/img/flags/pl.svg',
                                                			'skins/Weather34/img/flags/pol.svg',
                                                			'skins/Weather34/img/flags/pt.svg',
                                                			'skins/Weather34/img/flags/sa.svg',
                                                			'skins/Weather34/img/flags/scot.svg',
                                                			'skins/Weather34/img/flags/singapore.svg',
                                                			'skins/Weather34/img/flags/sp.svg',
                                                			'skins/Weather34/img/flags/sw.svg',
                                                			'skins/Weather34/img/flags/tr.svg',
                                                			'skins/Weather34/img/flags/uk.svg',
                                                			'skins/Weather34/img/flags/us.svg',
                                                			'skins/Weather34/img/flags/wal.svg']),


                    ('skins/Weather34/js',   ['skins/Weather34/js/jquery.js',
                                                        'skins/Weather34/js/marchjquery.js',
                                                		'skins/Weather34/js/oldjquery.js'
                                                       		]), 

					('skins/Weather34/jsondata',   						['skins/Weather34/jsondata/place.holder'
														 
                                                       								]),

					('skins/Weather34/languages',   ['skins/Weather34/languages/lang.blank.php',
                                                        'skins/Weather34/languages/lang.cat.php',
														'skins/Weather34/languages/lang.dk.php',
														'skins/Weather34/languages/lang.dl.php',
														'skins/Weather34/languages/lang.en.php',
														'skins/Weather34/languages/lang.fr.php',
														'skins/Weather34/languages/lang.gr.php',
														'skins/Weather34/languages/lang.hu.php',
														'skins/Weather34/languages/lang.it.php',
														'skins/Weather34/languages/lang.nl.php',
														'skins/Weather34/languages/lang.no.php',
														'skins/Weather34/languages/lang.pl.php',
														'skins/Weather34/languages/lang.sp.php',
														'skins/Weather34/languages/lang.sw.php',
														'skins/Weather34/languages/lang.tr.php'
                                                		
                                                       		]),

					('skins/Weather34/w34charts',   						['skins/Weather34/w34charts/canvasJs.js',
                                                        							'skins/Weather34/w34charts/chart_theme.php',
														
														'skins/Weather34/w34charts/empty.php',
														'skins/Weather34/w34charts/license.txt',
														'skins/Weather34/w34charts/monthlybarometer.php',
														'skins/Weather34/w34charts/monthlydewpoint.php',
														'skins/Weather34/w34charts/monthlyrainfall.php',
														'skins/Weather34/w34charts/monthlysolar.php',
														'skins/Weather34/w34charts/monthlytemperature.php',
														'skins/Weather34/w34charts/monthlywindspeedgust.php',
														'skins/Weather34/w34charts/todaybarometer.php',
														'skins/Weather34/w34charts/todayrainfall.php',
														'skins/Weather34/w34charts/todaysolar.php',
														'skins/Weather34/w34charts/todaysolarsmall.php',
														'skins/Weather34/w34charts/todaytemperature.php',
														'skins/Weather34/w34charts/todayuv.php',
														'skins/Weather34/w34charts/todayuvsmall.php',
														'skins/Weather34/w34charts/todaywinddirection.php',
														'skins/Weather34/w34charts/todaywindspeedgust.php',
														'skins/Weather34/w34charts/weather34chartstyle-dark.css',
														'skins/Weather34/w34charts/weather34chartstyle-light.css',
														'skins/Weather34/w34charts/yearlybarometer.php',
														'skins/Weather34/w34charts/yearlybarometermedium.php',
														'skins/Weather34/w34charts/yearlydewpoint.php',
														'skins/Weather34/w34charts/yearlyrainfall.php',
														'skins/Weather34/w34charts/yearlyrainfallmedium.php',
														'skins/Weather34/w34charts/yearlysolar.php',
														'skins/Weather34/w34charts/yearlytemperature.php',
														'skins/Weather34/w34charts/yearlytemperaturemedium.php',
														'skins/Weather34/w34charts/yearlywindspeedgust.php',
														'skins/Weather34/w34charts/yearlywindspeedgustmedium.php'
                                                		
                                                       		]),
		   			('skins/Weather34/w34charts/chartdata', 					['skins/Weather34/w34charts/chartdata/result.csv.tmpl',
                                        									'skins/Weather34/w34charts/chartdata/MMYYYY.csv.tmpl',
                                       										'skins/Weather34/w34charts/chartdata//YYYY.csv.tmpl'
		   												]),

					('skins/Weather34/metar',   						['skins/Weather34/metar/metar34get.php'	
														]),									   


                   
                   ])
